// JS Ridge Regression Engine
// Exactly reconstructs the sklearn pipeline: StandardScaler → OneHotEncoder → Ridge
// Loaded from /public/data/model_weights.json which is generated by export_model_weights.py

import { ModelWeights, PredictorInputs } from './types';

/**
 * Predict a rating (0-10) for a drink profile using the exported Ridge Regression weights.
 * Reconstructs: StandardScaler(numeric) + OneHotEncoder(categorical) → Ridge
 */
export function predict(inputs: PredictorInputs, weights: ModelWeights): number {
  const features: number[] = [];

  // 1. Numeric features — apply StandardScaler: z = (x - mean) / std
  const numericValues: Record<string, number> = {
    sweetness_level: inputs.sweetness_level,
    tartness_level: inputs.tartness_level,
    carbonation_level: inputs.carbonation_level,
    artificial_sweetener_taste: inputs.artificial_sweetener_taste,
    smoothness: inputs.smoothness,
    refreshing_score: inputs.refreshing_score,
    sugar_free: inputs.sugar_free ? 1 : 0,
  };

  weights.numeric_features.forEach((feat, i) => {
    const val = numericValues[feat] ?? 0;
    const scaled = (val - weights.numeric_means[i]) / weights.numeric_stds[i];
    features.push(scaled);
  });

  // 2. Categorical features — OneHotEncoder (handle_unknown='ignore')
  // categorical_features = ['primary_flavor_category', 'brand']
  const categoricalValues: Record<string, string> = {
    primary_flavor_category: inputs.primary_flavor_category,
    brand: inputs.brand,
  };

  weights.categorical_features.forEach((feat, fi) => {
    const categories = weights.categorical_categories[fi];
    const val = categoricalValues[feat] ?? '';
    categories.forEach((cat) => {
      features.push(cat === val ? 1 : 0);
    });
  });

  // 3. Linear: dot(features, coefficients) + intercept
  let prediction = weights.intercept;
  for (let i = 0; i < features.length; i++) {
    prediction += features[i] * weights.coefficients[i];
  }

  // Clamp to [0, 10]
  return Math.max(0, Math.min(10, prediction));
}

/**
 * Find the top N most similar reviewed drinks using Euclidean distance on taste features
 */
export function findSimilar(inputs: PredictorInputs, reviews: import('./types').Review[], n = 3) {
  const numericKeys = [
    'sweetness_level', 'tartness_level', 'carbonation_level',
    'artificial_sweetener_taste', 'smoothness', 'refreshing_score'
  ] as const;

  const inputVec = numericKeys.map(k => (inputs as Record<string, number>)[k] ?? 3);

  const scored = reviews
    .filter(r => r.rating > 0)
    .map(r => {
      const rVec = numericKeys.map(k => r[k as keyof typeof r] as number ?? 3);
      const dist = Math.sqrt(inputVec.reduce((acc, v, i) => acc + Math.pow(v - rVec[i], 2), 0));
      return { review: r, dist };
    })
    .sort((a, b) => a.dist - b.dist);

  return scored.slice(0, n).map(s => s.review);
}

/**
 * Get a comic-style verdict string based on predicted rating
 */
export function getVerdict(rating: number): { label: string; color: string; bg: string; exclaim: string } {
  if (rating >= 9.0) return { label: 'LEGENDARY', color: '#002020', bg: '#00fbfb', exclaim: 'BAM!' };
  if (rating >= 8.0) return { label: 'EXCELLENT', color: '#002020', bg: '#00dddd', exclaim: 'ZAP!' };
  if (rating >= 7.0) return { label: 'SOLID', color: '#1d1d00', bg: '#eaea00', exclaim: 'POW!' };
  if (rating >= 6.0) return { label: 'DECENT', color: '#1d1d00', bg: '#eded00', exclaim: 'WHAM!' };
  if (rating >= 5.0) return { label: 'MEH', color: '#ffffff', bg: '#a900a9', exclaim: 'UGH!' };
  return { label: 'DANGER ZONE', color: '#ffffff', bg: '#ba1a1a', exclaim: 'CRASH!' };
}
